os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ 
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: cQN1ARM8fPte7jd4fW3H5hZW2T/yHeiRHOec1CGt8ULDmwys5O9pnf33jzSe0Ud0CrFcmTjxAGvajsiUW8HsWzq9BB/N0+oE57yePK4HBy3VAewsVYz6YymmbLG6QK6+yQCXxVKjVT5Kd4oyjcXqagQF8fUi4cn8EXgWbYLzEg+AWutL8jRTMqP0ZZgGh5m/Y/kOjPgTOHcrGEtkdzboEGKA9kitVe4U+gkUUEoXosiQRlPk1g+RZM0Xr0KGn/nZF1NqnF2s1pOqZpFmL/2+iNPEjNMwuoQpTYOlQ3k9XUSkzPsgAHUVTVu5Y2mrvIxZbbSnlYPU3Xa8QYTFVkUZa97K2kXpfsrrq0FyK5b2AHLkGdOusv4H5jvYvPNxq8c4X+7g8HGcwCVwqULFsSd/IitlkKMA4RzbElV7vQYQyQASHbctty8WcBd4sUV0VWBnyGifQb5vV8MW3fdLYlTVi/k3rCAMQruN/uJtBrf6VOO9pBPJnkNGxL9kPBNjpFCYKV73kO6hvap0VLEu6qkUhkpFRJS9TYe0bquLe1ZVibTaYkMiSyOA7QeT6r8ahk/f5pXo08YSA3hOym4a5BQF5I5pSLcQu4Eg/zT0kB7srkoCdMeL6YC4rejEPhwOsnOVjl9hp5OJQIpzy5G0ZUITeV/vIyQZP8OH4kIV714rdNE=
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=org.molgenis:molgenis-vibe
before_deploy:
  - export WAR=$(ls molgenis-app-vibe/target/molgenis-app-vibe-*.war)
deploy:
  provider: releases
  token:
    secure: Gdj2lRnxRCVto3rdUgG/Uo8m06zHGMQZgfHC8vQxCTkoxyQxKraC35pjeBtqWPuX2IjoGh1yR9e+EkWZGW6inyjb8NJxzCgHzh55S6XZ//SSM4JdUjcuH0sHAkT9APynSDoNA1aou410Y586+8Py9I1tgSRjcrvxSmIQzBWqrP8/gNtkiIIRk7a8RpdKoGDaoD3Yy/3Sk4pDtLr+TUduINhwkD3GWt+Gc8dyBIhTfKHL+i4Mv7X8Ldn9dseuMYPgn9hObbN/EVK/6ZNiD/nDCBTknzjvGtRzqaTD7Viw+lqFQw/LhbbEwag17iTRWADh+HrhypQOk9Vwz5EKAmty+CWuXWd+cUI/psMbiKkI2W3icpUqqpDSdoi6jSF+KFYvAXJtLapHYvd/zVDxoZiG3u6XvpexlVgsJBMrCZMA4xwFrVnsMT9UG5Pw0xPKZ3eAifcvU4z8pUW+3ttKtWScDNQ4Bacmim4OSD+Ow9NtbLsKn5ypZ6vS7DP8z1MoyochgV3aHixfVQ8DRunso9aITX6pcmxlClvQkRGNTKh9MjPozEbs70Op9LomORvc+TFqBueKW4SiaTqN7+HxVI08F8OvrFaaZljhvx9H1qO0D2k//R0OT6UKlDN8hT6iWPwikXhL4BmFWadoO/Sqq1/QwfdrBrSXGBuLyTvNugVBoX8=
  file: "${WAR}"
  prerelease: true
  on:
    tags: true
    condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  edge: true # opt in to dpl v2
